export const PROPERTY_DETAILS = "PROPERTY_DETAILS"

export const PROP_DETAILS_START = "PROP_DETAILS_START"
export const PROP_DETAILS_SUCCESS = "PROP_DETAILS_SUCCESS"
export const PROP_DETAILS_FAIL = "PROP_DETAILS_FAIL"

export const PROP_RECO = "PROP_RECO"

export const PROP_BOOKING_START = "PROP_BOOKING_START"
export const PROP_BOOKING_SUCC = "PROP_BOOKING_SUCC"
export const PROP_BOOKING_FAIL = "PROP_BOOKING_FAIL"

export const CHANGE_START_DATE = "CHANGE_SATRT_DATE"
export const CHANGE_END_DATE = "CHANGE_END_DATE"
export const CHANGE_PRICE = "CHANGE_PRICE"

export const GUEST_DAYS = "GUEST_DAYS"