export const PROPERTY_DETAILS = "PROPERTY_DETAILS"

export const PROP_DETAILS_START = "PROP_DETAILS_START"
export const PROP_DETAILS_SUCCESS = "PROP_DETAILS_SUCCESS"
export const PROP_DETAILS_FAIL = "PROP_DETAILS_FAIL"


