"""empty message

Revision ID: 002ec01401a8
Revises: a68b4366f488
Create Date: 2020-07-24 13:18:31.925092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002ec01401a8'
down_revision = 'a68b4366f488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('child', sa.String(length=10), nullable=True),
    sa.Column('car', sa.String(length=10), nullable=True),
    sa.Column('ac', sa.String(length=10), nullable=True),
    sa.Column('pet', sa.String(length=10), nullable=True),
    sa.Column('beach', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('key_field')
    # ### end Alembic commands ###
