"""empty message

Revision ID: 334e4399c6aa
Revises: 2602f079b012
Create Date: 2020-07-26 19:40:01.899123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '334e4399c6aa'
down_revision = '2602f079b012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('rev_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('review', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('date', mysql.DATETIME(), nullable=True))
    op.drop_column('review', 'rev_date')
    # ### end Alembic commands ###
