"""empty message

Revision ID: 6e3570f8947c
Revises: 7c73b9ec8111
Create Date: 2020-07-25 15:34:22.663040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e3570f8947c'
down_revision = '7c73b9ec8111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('balcony', sa.String(length=10), nullable=True),
    sa.Column('staffed', sa.String(length=10), nullable=True),
    sa.Column('tv', sa.String(length=10), nullable=True),
    sa.Column('fans', sa.String(length=10), nullable=True),
    sa.Column('linen', sa.String(length=10), nullable=True),
    sa.Column('towels', sa.String(length=10), nullable=True),
    sa.Column('housekeeper', sa.String(length=10), nullable=True),
    sa.Column('wifi', sa.String(length=10), nullable=True),
    sa.Column('swimming_pool', sa.String(length=10), nullable=True),
    sa.Column('heated_pool', sa.String(length=10), nullable=True),
    sa.Column('washing_machine', sa.String(length=10), nullable=True),
    sa.Column('garden', sa.String(length=10), nullable=True),
    sa.Column('dvd', sa.String(length=10), nullable=True),
    sa.Column('grill', sa.String(length=10), nullable=True),
    sa.Column('fireplace', sa.String(length=10), nullable=True),
    sa.Column('cot', sa.String(length=10), nullable=True),
    sa.Column('dishwash', sa.String(length=10), nullable=True),
    sa.Column('microwave', sa.String(length=10), nullable=True),
    sa.Column('freezer', sa.String(length=10), nullable=True),
    sa.Column('game', sa.String(length=10), nullable=True),
    sa.Column('sea_view', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    op.create_table('suitability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('pets', sa.String(length=10), nullable=True),
    sa.Column('parking', sa.String(length=10), nullable=True),
    sa.Column('children', sa.String(length=10), nullable=True),
    sa.Column('smoke', sa.String(length=10), nullable=True),
    sa.Column('elevator', sa.String(length=10), nullable=True),
    sa.Column('wheelchair', sa.String(length=10), nullable=True),
    sa.Column('car_req', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    op.add_column('product', sa.Column('image_a', sa.String(length=200), nullable=True))
    op.add_column('product', sa.Column('image_b', sa.String(length=200), nullable=True))
    op.add_column('product', sa.Column('image_c', sa.String(length=200), nullable=True))
    op.add_column('product', sa.Column('image_d', sa.String(length=200), nullable=True))
    op.drop_column('product', 'access')
    op.drop_column('product', 'smoking')
    op.drop_column('product', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('product', sa.Column('smoking', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('product', sa.Column('access', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('product', 'image_d')
    op.drop_column('product', 'image_c')
    op.drop_column('product', 'image_b')
    op.drop_column('product', 'image_a')
    op.drop_table('suitability')
    op.drop_table('amenities')
    # ### end Alembic commands ###
