"""empty message

Revision ID: 77610afb88a3
Revises: c4de2fc8caa3
Create Date: 2020-07-24 00:44:58.231724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77610afb88a3'
down_revision = 'c4de2fc8caa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('bed', sa.Integer(), nullable=True),
    sa.Column('bath', sa.Integer(), nullable=True),
    sa.Column('no_people', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('access', sa.String(length=10), nullable=True),
    sa.Column('smoking', sa.String(length=10), nullable=True),
    sa.Column('minimum_stay', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
