"""empty message

Revision ID: 7c73b9ec8111
Revises: a38d4cfc473a
Create Date: 2020-07-24 17:29:27.026192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c73b9ec8111'
down_revision = 'a38d4cfc473a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suitability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('pets', sa.String(length=10), nullable=True),
    sa.Column('parking', sa.String(length=10), nullable=True),
    sa.Column('children', sa.String(length=10), nullable=True),
    sa.Column('smoke', sa.String(length=10), nullable=True),
    sa.Column('elevator', sa.String(length=10), nullable=True),
    sa.Column('wheelchair', sa.String(length=10), nullable=True),
    sa.Column('car_req', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suitability')
    # ### end Alembic commands ###
