"""empty message

Revision ID: 840f4e27cebf
Revises: c969f18cabb7
Create Date: 2020-07-30 18:26:56.637475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840f4e27cebf'
down_revision = 'c969f18cabb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('lat', sa.String(length=50), nullable=True))
    op.add_column('location', sa.Column('lng', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'lng')
    op.drop_column('location', 'lat')
    # ### end Alembic commands ###
