"""empty message

Revision ID: 852389fac640
Revises: 041681db1c98
Create Date: 2020-07-26 17:57:32.802021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '852389fac640'
down_revision = '041681db1c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
