"""empty message

Revision ID: a38d4cfc473a
Revises: 002ec01401a8
Create Date: 2020-07-24 17:21:12.126863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38d4cfc473a'
down_revision = '002ec01401a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('balcony', sa.String(length=10), nullable=True),
    sa.Column('staffed', sa.String(length=10), nullable=True),
    sa.Column('tv', sa.String(length=10), nullable=True),
    sa.Column('fans', sa.String(length=10), nullable=True),
    sa.Column('linen', sa.String(length=10), nullable=True),
    sa.Column('towels', sa.String(length=10), nullable=True),
    sa.Column('housekeeper', sa.String(length=10), nullable=True),
    sa.Column('wifi', sa.String(length=10), nullable=True),
    sa.Column('swimming_pool', sa.String(length=10), nullable=True),
    sa.Column('heated_pool', sa.String(length=10), nullable=True),
    sa.Column('washing_machine', sa.String(length=10), nullable=True),
    sa.Column('garden', sa.String(length=10), nullable=True),
    sa.Column('dvd', sa.String(length=10), nullable=True),
    sa.Column('grill', sa.String(length=10), nullable=True),
    sa.Column('fireplace', sa.String(length=10), nullable=True),
    sa.Column('cot', sa.String(length=10), nullable=True),
    sa.Column('dishwash', sa.String(length=10), nullable=True),
    sa.Column('microwave', sa.String(length=10), nullable=True),
    sa.Column('freezer', sa.String(length=10), nullable=True),
    sa.Column('game', sa.String(length=10), nullable=True),
    sa.Column('sea_view', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amenities')
    # ### end Alembic commands ###
