"""empty message

Revision ID: aba681187de5
Revises: 8f93d7b2cc9f
Create Date: 2020-07-30 05:37:00.035791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba681187de5'
down_revision = '8f93d7b2cc9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'status')
    # ### end Alembic commands ###
