"""empty message

Revision ID: f6d151985f6b
Revises: d4ac069b7c1a
Create Date: 2020-07-26 15:07:12.763885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d151985f6b'
down_revision = 'd4ac069b7c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ownerProperty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('english', sa.String(length=10), nullable=True),
    sa.Column('response_rate', sa.Integer(), nullable=True),
    sa.Column('year_listed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ownerProperty')
    # ### end Alembic commands ###
