"""empty message

Revision ID: fbc4feca4a2e
Revises: aba681187de5
Create Date: 2020-07-30 17:44:56.113437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc4feca4a2e'
down_revision = 'aba681187de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('lat', sa.Integer(), nullable=True))
    op.add_column('city', sa.Column('lng', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'lng')
    op.drop_column('city', 'lat')
    # ### end Alembic commands ###
